import { chromium } from 'playwright';
import { PDFDocument } from 'pdf-lib';
import fs from 'node:fs';
const out = process.argv[2];
const b = await chromium.launch();
const p = await b.newPage();
await p.goto('http://localhost:4174/?print', { waitUntil: 'networkidle' });
await p.evaluate(() => document.fonts.ready);
const pdf = await p.pdf({ preferCSSPageSize: true, printBackground: true });
await p.emulateMedia({ media: 'print' });
await p.setViewportSize({ width: 701, height: 1000 });
await p.screenshot({ path: 'cv-preview.png', fullPage: true });
await b.close();
const doc = await PDFDocument.load(pdf);
doc.setTitle('Muhammad Abdullah CV');
doc.setAuthor('Muhammad Abdullah');
doc.setSubject('Security Operations Analyst CV');
doc.setKeywords(['Security Operations Analyst', 'SOC', 'Incident Response', 'Elastic SIEM', 'Microsoft 365 Defender']);
doc.setCreator('Muhammad Abdullah');
doc.setProducer('Muhammad Abdullah');
fs.writeFileSync(out, await doc.save());
console.log('pages:', doc.getPageCount(), 'bytes:', fs.statSync(out).size);
